In [1]:
## imports
import pandas as pd
import numpy as np
import re
import requests
import yaml


## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 1. Example 1: no credentials; no wrapper

Site: National Assessment of Education Progress (NAEP)

Documentation: https://www.nationsreportcard.gov/api_documentation.aspx

Base link: https://www.nationsreportcard.gov/DataService/GetAdhocData.aspx

## 1.1 Query to pull some data

In [5]:
## using their example query of 2011 writing scores separated by gender
## based on here - https://stackoverflow.com/questions/40836749/pythonic-way-of-writing-a-single-line-long-string
## using the ( ) syntax to formulate a long
## string without linebreaks added
example_naep_query = (
'https://www.nationsreportcard.gov/'
'Dataservice/GetAdhocData.aspx?'
'type=data&subject=writing&grade=8&'
'subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2011')


example_naep_query

'https://www.nationsreportcard.gov/Dataservice/GetAdhocData.aspx?type=data&subject=writing&grade=8&subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2011'

In [7]:
## use requests to call the api
naep_resp = requests.get(example_naep_query)
naep_resp
print(type(naep_resp))

## get the json contents of the response 
## here, we're assuming valid response
naep_resp_j = naep_resp.json()
naep_resp_j

## with result, turn it into a dataframe
naep_resp_d = pd.DataFrame(naep_resp_j['result'])
naep_resp_d

<class 'requests.models.Response'>

{'status': 200,
 'result': [{'year': 2011,
   'sample': 'R3',
   'yearSampleLabel': '2011',
   'Cohort': 2,
   'CohortLabel': 'Grade 8',
   'stattype': 'MN:MN',
   'subject': 'WRI',
   'grade': 8,
   'scale': 'WRIRP',
   'jurisdiction': 'NP',
   'jurisLabel': 'National public',
   'variable': 'GENDER',
   'variableLabel': 'Gender',
   'varValue': '1',
   'varValueLabel': 'Male',
   'value': 139.099504632971,
   'isStatDisplayable': 1,
   'errorFlag': 0},
  {'year': 2011,
   'sample': 'R3',
   'yearSampleLabel': '2011',
   'Cohort': 2,
   'CohortLabel': 'Grade 8',
   'stattype': 'MN:MN',
   'subject': 'WRI',
   'grade': 8,
   'scale': 'WRIRP',
   'jurisdiction': 'NP',
   'jurisLabel': 'National public',
   'variable': 'GENDER',
   'variableLabel': 'Gender',
   'varValue': '2',
   'varValueLabel': 'Female',
   'value': 158.567104984955,
   'isStatDisplayable': 1,
   'errorFlag': 0}]}

,year,sample,yearSampleLabel,Cohort,CohortLabel,stattype,subject,grade,scale,jurisdiction,jurisLabel,variable,variableLabel,varValue,varValueLabel,value,isStatDisplayable,errorFlag
0,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Gender,1,Male,139.099505,1,0
1,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Gender,2,Female,158.567105,1,0

## 1.2 What happens if there's an error in our query?

In [9]:
## here's a query that from the documentation we know
## won't work since i modified year to 2025 which doesnt
## exist in the data
wrong_naep_query = (
'https://www.nationsreportcard.gov/'
'Dataservice/GetAdhocData.aspx?'
'type=data&subject=writing&grade=8&'
'subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2025')

wrong_naep_query

'https://www.nationsreportcard.gov/Dataservice/GetAdhocData.aspx?type=data&subject=writing&grade=8&subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2025'

In [11]:
## use requests to call the api
naep_wrong_resp = requests.get(wrong_naep_query)
naep_wrong_resp

In [13]:
## in the case of this particular api,
## the call returns some response but
## when we try to extract the json containing
## status or results, we get in an error
#naep_wrong_resp.json() # uncomment to see error

### 1.2.2 More all-purpose way of allowing remainder of calls to run: try, except

In [15]:
## putting it in a try; except as general error catching
try:
    results = naep_wrong_resp.json()['result']
except Exception as e:
    print('Failed to get result from API due to error:')
    print(e) # or just: pass

Failed to get result from API due to error:
Invalid control character at: line 1 column 289 (char 288)

### 1.2.3 Can usually also find more targeted way but that varies more across APIs

In [18]:
## if we wanted do more specific error catching,
## see that the status == 400 actually appears here
## so could write if else along those lines
naep_wrong_resp.text
naep_resp.text

if "System.Exception" in naep_wrong_resp.text:
    print("NAEP results not found")

'{"status":400,"result": "System.Exception: The query \'SELECT DISTINCT Framework FROM Cycles WHERE Subject=\'WRI\' AND Cohort=2 AND CONVERT(VARCHAR(10),Year)+Sample IN (\'2025R3\')\' did not return exactly 1 framework. Make sure you can trend the years defined for the given subject and cohort.\r\n   at NRCDataService3.GetAdhocData.GetFramework(NDEContext& ndeContext, String subjectCode, List`1 yearSamples, String cohort) in C:\\projects\\ndecore2015\\NRCDataService2\\GetAdhocData.aspx.cs:line 2380\r\n   at NRCDataService3.GetAdhocData.PopulateBaseOrchestratorRequest() in C:\\projects\\ndecore2015\\NRCDataService2\\GetAdhocData.aspx.cs:line 2010\r\n   at NRCDataService3.GetAdhocData.ConstructRequest_Datapoint() in C:\\projects\\ndecore2015\\NRCDataService2\\GetAdhocData.aspx.cs:line 651\r\n   at NRCDataService3.GetAdhocData.Page_Load(Object sender, EventArgs e) in C:\\projects\\ndecore2015\\NRCDataService2\\GetAdhocData.aspx.cs:line 191"}'

'{"status":200,"result": [{"year":2011,"sample":"R3","yearSampleLabel":"2011","Cohort":2,"CohortLabel":"Grade 8","stattype":"MN:MN","subject":"WRI","grade":8,"scale":"WRIRP","jurisdiction":"NP","jurisLabel":"National public","variable":"GENDER","variableLabel":"Gender","varValue":"1","varValueLabel":"Male","value":139.099504632971,"isStatDisplayable":1,"errorFlag":0},{"year":2011,"sample":"R3","yearSampleLabel":"2011","Cohort":2,"CohortLabel":"Grade 8","stattype":"MN:MN","subject":"WRI","grade":8,"scale":"WRIRP","jurisdiction":"NP","jurisLabel":"National public","variable":"GENDER","variableLabel":"Gender","varValue":"2","varValueLabel":"Female","value":158.567104984955,"isStatDisplayable":1,"errorFlag":0}]}'

NAEP results not found

## Activity 1: writing a function to make multiple, sequential calls

- Say we want to pull the data for grades 4, 8, and 12
- How can we write a function that iterates over a list of those grades and pulls the data for each grade?

**Note**: an ideal function would have arguments for each parameter in the API like subject, subscale, etc. Here we can leave those other parts constant

In [62]:
# your code here

import requests

def grade_data(grades, subject, subscale, base_url = "https://api.grades.com/data"):
    results = {}

    for grade in grades:
        parameters = {
            "grade" : grade,
            "subject" : subject,
            "subscale" : subscale
        }
        
        response = requests.get(base_url, params = parameters, verify = False)
        if response.status_code == 200:
            results[grade] = response.json()
        else:
            results[grade] = f"Error {response.status_code}: Unable to retrieve data."

    return results

In [64]:
grades = [4, 8, 12]
data_test = grade_data(grades, subject = "Math", subscale = "General")
data_test
# find a way to do this before PSET 3!!!!!

ConnectionError: HTTPSConnectionPool(host='api.grades.com', port=443): Max retries exceeded with url: /data?grade=4&subject=Math&subscale=General (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x16420bfb0>: Failed to resolve 'api.grades.com' ([Errno 8] nodename nor servname provided, or not known)"))

In [68]:
# ANSWER KEY

# grades = ['4','8','12']

def get_grades(grades):
    result = pd.DataFrame()
    
    for grade in grades: 
        example_naep_query = (
            'https://www.nationsreportcard.gov/'
            'Dataservice/GetAdhocData.aspx?'
            f'type=data&subject=writing&grade={grade}&'
            'subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2011')
        naep_resp = requests.get(example_naep_query)
        
        try: 
            naep_resp_j = naep_resp.json()
            naep_resp_j
            naep_resp_d = pd.DataFrame(naep_resp_j['result'])
            result = pd.concat([result,naep_resp_d]) 
        
        except Exception as e:
            print(e)
            
    return result

In [70]:
get_grades(['4', '7', '8','12'])

Invalid control character at: line 1 column 289 (char 288)
DataFrame constructor not properly called!

,year,sample,yearSampleLabel,Cohort,CohortLabel,stattype,subject,grade,scale,jurisdiction,jurisLabel,variable,variableLabel,varValue,varValueLabel,value,isStatDisplayable,errorFlag
0,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Gender,1,Male,139.099505,1,0
1,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Gender,2,Female,158.567105,1,0
0,2011,R3,2011,3,Grade 12,MN:MN,WRI,12,WRIRP,NP,National public,GENDER,Gender,1,Male,141.256978,1,0
1,2011,R3,2011,3,Grade 12,MN:MN,WRI,12,WRIRP,NP,National public,GENDER,Gender,2,Female,155.385917,1,0

# 2. Example 2: needs credentials; no wrapper

Create an account here: https://www.yelp.com/developers/v3/manage_app

In [72]:
## get the key
API_KEY = "zCRt4-fpDeSD35_j92iBh8oBgJu4FeOrS8ddOizwFKdgLqJaPP1IbaLwADvthHZjIAwlK59Js4ZLkPpShzMsvziRka6nHRR7E5ngSkWLfELbKWvkF3YBIkTuemYaZ3Yx"

In [74]:
## use documentation to define what to search
## doc: https://www.yelp.com/developers/documentation/v3/business_search
## write the query 
base_url = "https://api.yelp.com/v3/businesses/search?"
my_name = "restaurants"
my_location = "Hanover,NH,03755"
yelp_genquery = ('{base_url}'
                'term={name}'
                '&location={loc}').format(base_url = base_url,
                name = my_name,
                loc = my_location)

## use requests to call the API; here, we're
## passing it our credentials (structure varies
## by API and telling it to only return 10 results
## (max is 50 at once)
header = {'Authorization': f"Bearer {API_KEY}"}
yelp_genresp = requests.get(yelp_genquery, headers = header)
yelp_genresp

## then, look at structure of response
yelp_genjson = yelp_genresp.json()

In [76]:
## example business
yelp_genjson['businesses'][0]

## more automatic way of summarizing but things end up in lists
## within columns for things like categories
yelp_gendf = pd.DataFrame(yelp_genjson['businesses'])
yelp_gendf.head()

{'id': 'XVGEEIH5rVB2QzW-qywcJw',
 'alias': 'base-camp-cafe-hanover',
 'name': 'Base Camp Cafe',
 'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/p8_YiEQI7p_JF82eaWa9Xg/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/base-camp-cafe-hanover?adjust_creative=pFGjfkFyX0dejDh2Pl7Cpg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=pFGjfkFyX0dejDh2Pl7Cpg',
 'review_count': 252,
 'categories': [{'alias': 'himalayan', 'title': 'Himalayan/Nepalese'}],
 'rating': 4.4,
 'coordinates': {'latitude': 43.700626, 'longitude': -72.2887803},
 'transactions': ['delivery'],
 'price': '$$',
 'location': {'address1': '3 Lebanon St',
  'address2': 'Ste 13',
  'address3': '',
  'city': 'Hanover',
  'zip_code': '03755',
  'country': 'US',
  'state': 'NH',
  'display_address': ['3 Lebanon St', 'Ste 13', 'Hanover, NH 03755']},
 'phone': '+16036432007',
 'display_phone': '(603) 643-2007',
 'distance': 196.1397581876442,
 'business_hours': [{'open': [{'is_overnight': False,
     'start': '1100',
     'end': '2100',
     'day': 1},
    {'is_overnight': False, 'start': '1100', 'end': '2100', 'day': 2},
    {'is_overnight': False, 'start': '1100', 'end': '2100', 'day': 3},
    {'is_overnight': False, 'start': '1100', 'end': '2130', 'day': 4},
    {'is_overnight': False, 'start': '1100', 'end': '2130', 'day': 5},
    {'is_overnight': False, 'start': '1100', 'end': '2100', 'day': 6}],
   'hours_type': 'REGULAR',
   'is_open_now': True}],
 'attributes': {'business_temp_closed': None,
  'menu_url': 'http://basecampcafenewhampshire.com/menu/',
  'open24_hours': None,
  'waitlist_reservation': None}}

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,business_hours,attributes
0,XVGEEIH5rVB2QzW-qywcJw,base-camp-cafe-hanover,Base Camp Cafe,https://s3-media1.fl.yelpcdn.com/bphoto/p8_YiE...,False,https://www.yelp.com/biz/base-camp-cafe-hanove...,252,"[{'alias': 'himalayan', 'title': 'Himalayan/Ne...",4.4,"{'latitude': 43.700626, 'longitude': -72.2887803}",[delivery],$$,"{'address1': '3 Lebanon St', 'address2': 'Ste ...",+16036432007,(603) 643-2007,196.139758,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
1,8ybF6YyRldtZmU9jil4xlg,mollys-restaurant-and-bar-hanover,Molly's Restaurant & Bar,https://s3-media4.fl.yelpcdn.com/bphoto/TJLrrA...,False,https://www.yelp.com/biz/mollys-restaurant-and...,545,"[{'alias': 'tradamerican', 'title': 'American'...",3.9,"{'latitude': 43.701144, 'longitude': -72.2894249}",[delivery],$$,"{'address1': '43 South Main St', 'address2': '...",+16036432570,(603) 643-2570,250.830160,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
2,qxm3VNmD0O2zw8m9U8SxZg,duende-hanover-2,Duende,https://s3-media4.fl.yelpcdn.com/bphoto/rf_h2D...,False,https://www.yelp.com/biz/duende-hanover-2?adju...,15,"[{'alias': 'spanish', 'title': 'Spanish'}, {'a...",3.7,"{'latitude': 43.70074272457673, 'longitude': -...",[],NaN,"{'address1': '15 Lebanon St', 'address2': '', ...",+16033064826,(603) 306-4826,107.388862,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
3,5WW4g_LRwau29KyjZGLyAA,sawtooth-kitchen-hanover,Sawtooth Kitchen,https://s3-media3.fl.yelpcdn.com/bphoto/61MNG4...,False,https://www.yelp.com/biz/sawtooth-kitchen-hano...,29,"[{'alias': 'chickenshop', 'title': 'Chicken Sh...",4.1,"{'latitude': 43.70158, 'longitude': -72.289641}",[],NaN,"{'address1': '33 S Main St', 'address2': '', '...",+16036435134,(603) 643-5134,242.607552,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
4,wyV_NfYn4ZOfp_sHMDPcAw,bistro-at-six-hanover,Bistro at Six,https://s3-media2.fl.yelpcdn.com/bphoto/i4jvss...,False,https://www.yelp.com/biz/bistro-at-six-hanover...,2,"[{'alias': 'lounges', 'title': 'Lounges'}, {'a...",4.0,"{'latitude': 43.7001146, 'longitude': -72.2877...",[],$$,"{'address1': '6 E South St', 'address2': None,...",+16036430600,(603) 643-0600,198.651788,"[{'open': [{'is_overnight': True, 'start': '00...","{'business_temp_closed': None, 'menu_url': Non..."

In [78]:
## more data-specific way of summarizing
## we're doing a simple approach and just retaining
## cols that have a simple str structure
## if doing for real, would want to extract things
def clean_yelp_json(one_biz):

    ## restrict to str cols
    d_str = {key:value for key, value in one_biz.items()
             if type(value) == str}
    
    df_str = pd.DataFrame(d_str, index = [d_str['id']])
    return(df_str)

yelp_stronly = [clean_yelp_json(one_b) for one_b in yelp_genjson['businesses']]
yelp_stronly_df = pd.concat(yelp_stronly)

yelp_stronly_df.head(7)

,id,alias,name,image_url,url,price,phone,display_phone
XVGEEIH5rVB2QzW-qywcJw,XVGEEIH5rVB2QzW-qywcJw,base-camp-cafe-hanover,Base Camp Cafe,https://s3-media1.fl.yelpcdn.com/bphoto/p8_YiE...,https://www.yelp.com/biz/base-camp-cafe-hanove...,$$,+16036432007,(603) 643-2007
8ybF6YyRldtZmU9jil4xlg,8ybF6YyRldtZmU9jil4xlg,mollys-restaurant-and-bar-hanover,Molly's Restaurant & Bar,https://s3-media4.fl.yelpcdn.com/bphoto/TJLrrA...,https://www.yelp.com/biz/mollys-restaurant-and...,$$,+16036432570,(603) 643-2570
qxm3VNmD0O2zw8m9U8SxZg,qxm3VNmD0O2zw8m9U8SxZg,duende-hanover-2,Duende,https://s3-media4.fl.yelpcdn.com/bphoto/rf_h2D...,https://www.yelp.com/biz/duende-hanover-2?adju...,NaN,+16033064826,(603) 306-4826
5WW4g_LRwau29KyjZGLyAA,5WW4g_LRwau29KyjZGLyAA,sawtooth-kitchen-hanover,Sawtooth Kitchen,https://s3-media3.fl.yelpcdn.com/bphoto/61MNG4...,https://www.yelp.com/biz/sawtooth-kitchen-hano...,NaN,+16036435134,(603) 643-5134
wyV_NfYn4ZOfp_sHMDPcAw,wyV_NfYn4ZOfp_sHMDPcAw,bistro-at-six-hanover,Bistro at Six,https://s3-media2.fl.yelpcdn.com/bphoto/i4jvss...,https://www.yelp.com/biz/bistro-at-six-hanover...,$$,+16036430600,(603) 643-0600
KA8yhrd-ClVYMyOefXdVYg,KA8yhrd-ClVYMyOefXdVYg,lous-restaurant-and-bakery-hanover,Lou's Restaurant & Bakery,https://s3-media3.fl.yelpcdn.com/bphoto/VAx8H9...,https://www.yelp.com/biz/lous-restaurant-and-b...,$$,+16036433321,(603) 643-3321
34j_2nRCVQBTKafJvncZlg,34j_2nRCVQBTKafJvncZlg,pine-restaurant-hanover-2,PINE Restaurant,https://s3-media3.fl.yelpcdn.com/bphoto/c2SgUR...,https://www.yelp.com/biz/pine-restaurant-hanov...,$$$,+16036468000,(603) 646-8000

# Activity 2: pull restaurants in a different location

- Try running a business search query for your hometown or another place by constructing a query similar to `yelp_genquery` but changing the location parameter
- Other endpoints require feeding what's called the business' fusion id into the API. Take an id from `yelp_stronly.id` and use the documentation here to pull the reviews for that business: https://docs.developer.yelp.com/reference/v3_business_reviews
- **Challenge**: generalize the previous step by writing a function that (1) takes a list of business ids as an input, (2) calls the reviews API for each id, (3) returns the results, and (4) rowbinds all results, i.e. turns them into a single, usable DataFrame

In [118]:
# your code here

## use documentation to define what to search
## doc: https://www.yelp.com/developers/documentation/v3/business_search
## write the query 
base_url = "https://api.yelp.com/v3/businesses/search?"
my_name = "restaurants"
my_location = "Manhattan,NY,10001"
yelp_genquery = ('{base_url}'
                'term={name}'
                '&location={loc}').format(base_url = base_url,
                name = my_name,
                loc = my_location)

## use requests to call the API; here, we're
## passing it our credentials (structure varies
## by API and telling it to only return 10 results
## (max is 50 at once)
header = {'Authorization': f"Bearer {API_KEY}"}
yelp_genresp = requests.get(yelp_genquery, headers = header)
yelp_genresp

## then, look at structure of response
yelp_genjson = yelp_genresp.json()

In [120]:
## example business
yelp_genjson['businesses'][0]

## more automatic way of summarizing but things end up in lists
## within columns for things like categories
yelp_gendf = pd.DataFrame(yelp_genjson['businesses'])
yelp_gendf.head()

{'id': 'DEp-9JVnKN7eTb9A_mUlfA',
 'alias': 'zou-zou-s-new-york-3',
 'name': 'Zou Zou’s',
 'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/JFsmaq8GfDlzJJecw_bLHw/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/zou-zou-s-new-york-3?adjust_creative=pFGjfkFyX0dejDh2Pl7Cpg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=pFGjfkFyX0dejDh2Pl7Cpg',
 'review_count': 426,
 'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
  {'alias': 'cocktailbars', 'title': 'Cocktail Bars'},
  {'alias': 'newamerican', 'title': 'New American'}],
 'rating': 4.2,
 'coordinates': {'latitude': 40.75294111375021,
  'longitude': -73.99872428597398},
 'transactions': [],
 'price': '$$$',
 'location': {'address1': '385 9th Ave',
  'address2': 'Ste 85',
  'address3': None,
  'city': 'New York',
  'zip_code': '10001',
  'country': 'US',
  'state': 'NY',
  'display_address': ['385 9th Ave', 'Ste 85', 'New York, NY 10001']},
 'phone': '+12123808585',
 'display_phone': '(212) 380-8585',
 'distance': 248.50993127892994,
 'business_hours': [{'open': [{'is_overnight': False,
     'start': '1130',
     'end': '1430',
     'day': 0},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 0},
    {'is_overnight': False, 'start': '1130', 'end': '1430', 'day': 1},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 1},
    {'is_overnight': False, 'start': '1130', 'end': '1430', 'day': 2},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 2},
    {'is_overnight': False, 'start': '1130', 'end': '1430', 'day': 3},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 3},
    {'is_overnight': False, 'start': '1130', 'end': '1430', 'day': 4},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 4},
    {'is_overnight': False, 'start': '1100', 'end': '1430', 'day': 5},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 5},
    {'is_overnight': False, 'start': '1100', 'end': '1430', 'day': 6},
    {'is_overnight': False, 'start': '1700', 'end': '2300', 'day': 6}],
   'hours_type': 'REGULAR',
   'is_open_now': True}],
 'attributes': {'business_temp_closed': None,
  'menu_url': 'https://www.zouzousnyc.com/menus/',
  'open24_hours': None,
  'waitlist_reservation': None}}

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,business_hours,attributes
0,DEp-9JVnKN7eTb9A_mUlfA,zou-zou-s-new-york-3,Zou Zou’s,https://s3-media1.fl.yelpcdn.com/bphoto/JFsmaq...,False,https://www.yelp.com/biz/zou-zou-s-new-york-3?...,426,"[{'alias': 'mediterranean', 'title': 'Mediterr...",4.2,"{'latitude': 40.75294111375021, 'longitude': -...",[],$$$,"{'address1': '385 9th Ave', 'address2': 'Ste 8...",+12123808585,(212) 380-8585,248.509931,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
1,cJ837cA4SILruB3ArOZiSw,bourbon-and-branch-new-york-city,Bourbon and Branch,https://s3-media4.fl.yelpcdn.com/bphoto/fcnNvy...,False,https://www.yelp.com/biz/bourbon-and-branch-ne...,137,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.5,"{'latitude': 40.75030160000001, 'longitude': -...",[],NaN,"{'address1': '155 W 33rd St', 'address2': None...",+19294194951,(929) 419-4951,510.347031,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non..."
2,LkV96_buOU_n0br4SBO57w,ci-siamo-new-york-5,Ci Siamo,https://s3-media2.fl.yelpcdn.com/bphoto/IOo8N8...,False,https://www.yelp.com/biz/ci-siamo-new-york-5?a...,591,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.4,"{'latitude': 40.75240549384363, 'longitude': -...",[],$$$,"{'address1': '440 West 33rd St', 'address2': '...",+12122196559,(212) 219-6559,189.358070,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
3,eMqKFQbKQXq82EUVnlPguw,bar-primi-penn-district-new-york-3,Bar Primi Penn District,https://s3-media1.fl.yelpcdn.com/bphoto/HOyHsq...,False,https://www.yelp.com/biz/bar-primi-penn-distri...,76,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.2,"{'latitude': 40.7524583, 'longitude': -73.9954...","[delivery, pickup]",NaN,"{'address1': '349 W 33rd St', 'address2': None...",+12122336100,(212) 233-6100,76.875531,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': 'ht..."
4,VvsZAnEwU4c8Xkyrzx05Nw,anytime-kitchen-new-york-2,Anytime Kitchen,https://s3-media3.fl.yelpcdn.com/bphoto/APN3od...,False,https://www.yelp.com/biz/anytime-kitchen-new-y...,3059,"[{'alias': 'korean', 'title': 'Korean'}, {'ali...",4.6,"{'latitude': 40.74776270790539, 'longitude': -...","[pickup, delivery, restaurant_reservation]",$$,"{'address1': '23 W 32nd St', 'address2': 'Fl 3...",+16466697733,(646) 669-7733,910.824908,"[{'open': [{'is_overnight': False, 'start': '1...","{'business_temp_closed': None, 'menu_url': Non..."

In [122]:
## more data-specific way of summarizing
## we're doing a simple approach and just retaining
## cols that have a simple str structure
## if doing for real, would want to extract things
def clean_yelp_json(one_biz):

    ## restrict to str cols
    d_str = {key:value for key, value in one_biz.items()
             if type(value) == str}
    
    df_str = pd.DataFrame(d_str, index = [d_str['id']])
    return(df_str)

yelp_stronly = [clean_yelp_json(one_b) for one_b in yelp_genjson['businesses']]
yelp_stronly_df = pd.concat(yelp_stronly)

yelp_stronly_df.head(7)

,id,alias,name,image_url,url,price,phone,display_phone
DEp-9JVnKN7eTb9A_mUlfA,DEp-9JVnKN7eTb9A_mUlfA,zou-zou-s-new-york-3,Zou Zou’s,https://s3-media1.fl.yelpcdn.com/bphoto/JFsmaq...,https://www.yelp.com/biz/zou-zou-s-new-york-3?...,$$$,+12123808585,(212) 380-8585
cJ837cA4SILruB3ArOZiSw,cJ837cA4SILruB3ArOZiSw,bourbon-and-branch-new-york-city,Bourbon and Branch,https://s3-media4.fl.yelpcdn.com/bphoto/fcnNvy...,https://www.yelp.com/biz/bourbon-and-branch-ne...,NaN,+19294194951,(929) 419-4951
LkV96_buOU_n0br4SBO57w,LkV96_buOU_n0br4SBO57w,ci-siamo-new-york-5,Ci Siamo,https://s3-media2.fl.yelpcdn.com/bphoto/IOo8N8...,https://www.yelp.com/biz/ci-siamo-new-york-5?a...,$$$,+12122196559,(212) 219-6559
eMqKFQbKQXq82EUVnlPguw,eMqKFQbKQXq82EUVnlPguw,bar-primi-penn-district-new-york-3,Bar Primi Penn District,https://s3-media1.fl.yelpcdn.com/bphoto/HOyHsq...,https://www.yelp.com/biz/bar-primi-penn-distri...,NaN,+12122336100,(212) 233-6100
VvsZAnEwU4c8Xkyrzx05Nw,VvsZAnEwU4c8Xkyrzx05Nw,anytime-kitchen-new-york-2,Anytime Kitchen,https://s3-media3.fl.yelpcdn.com/bphoto/APN3od...,https://www.yelp.com/biz/anytime-kitchen-new-y...,$$,+16466697733,(646) 669-7733
V3USzFEGhuoXez4G2Rk11A,V3USzFEGhuoXez4G2Rk11A,tavola-new-york,Tavola,https://s3-media1.fl.yelpcdn.com/bphoto/HhhlKQ...,https://www.yelp.com/biz/tavola-new-york?adjus...,$$$,+12122731181,(212) 273-1181
pBNMZp_tKCAfRNx7-ybcHQ,pBNMZp_tKCAfRNx7-ybcHQ,calle-dao-chelsea-new-york-3,Calle Dao Chelsea,https://s3-media2.fl.yelpcdn.com/bphoto/GR36FB...,https://www.yelp.com/biz/calle-dao-chelsea-new...,$$,+12124144104,(212) 414-4104